name: run-tests

on:
  push:
    branches:
      - main
      - dev-main
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis
      DB_CONNECTION: testing
      APP_KEY: base64:2fl+Ktvkfl+Fuz3Qp/A76G2RTiGVA/ZjKZaz6fiiM10=
      APP_ENV: testing
      BCRYPT_ROUNDS: 10
      MAIL_MAILER: array
      TELESCOPE_ENABLED: false

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Setup PHP 🏗
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo, mysql

      - name: Install Project Dependencies 💻
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: List Installed Dependencies 📦
        run: composer show -D

      - name: Run tests 🧪
        run: |
          ./vendor/bin/pest  --version
          ./vendor/bin/pest
